// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Lykke.Service.EmailSender;

namespace Lykke.Service.EmailFormatter.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.EmailFormatter;
    using Lykke.Service.EmailFormatter.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    internal partial class EmailFormatResponse
    {
        /// <summary>
        /// Initializes a new instance of the EmailFormatResponse class.
        /// </summary>
        public EmailFormatResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailFormatResponse class.
        /// </summary>
        public EmailFormatResponse(EmailMessage emailMessage = default(EmailMessage))
        {
            EmailMessage = emailMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailMessage")]
        public EmailMessage EmailMessage { get; set; }

    }
}
