// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.TemplateFormatter.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmailAttachment
    {
        /// <summary>
        /// Initializes a new instance of the EmailAttachment class.
        /// </summary>
        public EmailAttachment()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailAttachment class.
        /// </summary>
        public EmailAttachment(string fileName = default(string), string mimeType = default(string), string contentInBase64 = default(string))
        {
            FileName = fileName;
            MimeType = mimeType;
            ContentInBase64 = contentInBase64;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MimeType")]
        public string MimeType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContentInBase64")]
        public string ContentInBase64 { get; set; }

    }
}
