// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.TemplateFormatter.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmailFormatResponse
    {
        /// <summary>
        /// Initializes a new instance of the EmailFormatResponse class.
        /// </summary>
        public EmailFormatResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailFormatResponse class.
        /// </summary>
        public EmailFormatResponse(EmailMessage emailMessage = default(EmailMessage))
        {
            EmailMessage = emailMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmailMessage")]
        public EmailMessage EmailMessage { get; set; }

    }
}
