// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.TemplateFormatter.Client.AutorestClient
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for TemplateFormatterAPI.
    /// </summary>
    public static partial class TemplateFormatterAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='caseId'>
            /// </param>
            /// <param name='partnerId'>
            /// </param>
            /// <param name='language'>
            /// </param>
            /// <param name='parameters'>
            /// </param>
            public static EmailFormatResponse ApiFormatterByCaseIdByPartnerIdByLanguagePost(this ITemplateFormatterAPI operations, string caseId, string partnerId, string language, IDictionary<string, string> parameters = default(IDictionary<string, string>))
            {
                return operations.ApiFormatterByCaseIdByPartnerIdByLanguagePostAsync(caseId, partnerId, language, parameters).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='caseId'>
            /// </param>
            /// <param name='partnerId'>
            /// </param>
            /// <param name='language'>
            /// </param>
            /// <param name='parameters'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<EmailFormatResponse> ApiFormatterByCaseIdByPartnerIdByLanguagePostAsync(this ITemplateFormatterAPI operations, string caseId, string partnerId, string language, IDictionary<string, string> parameters = default(IDictionary<string, string>), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiFormatterByCaseIdByPartnerIdByLanguagePostWithHttpMessagesAsync(caseId, partnerId, language, parameters, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object IsAlive(this ITemplateFormatterAPI operations)
            {
                return operations.IsAliveAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Checks service is alive
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> IsAliveAsync(this ITemplateFormatterAPI operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.IsAliveWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
